### ISSUE TITLE
Solutions to the problem you mention in report 3.14.1

### ISSUE THREAD

**Issue by Michael1015198808** [FluorineDog/hust-pa#1]
As you mentioned in 3.14.1, before initializing eflags, difftest may tell you that eflags of NEMU(host) and QEMU are different. As mentioned in [PA lecture](https://nju-ics.gitbooks.io/ics2018-programming-assignment/3.2.html), you can handle this by simply initialize eflags as 0x2 in restart function.
Further more, 0x2 may seems like a 'magic number' to you. Another solution is, once QEMU finished initializing, call gdb_getregs to make sure that NEMU(host)'s registers have exactly the same value as in QEMU

**Comment by FluorineDog** [comment]
Well, what I'm talking about at 3.14.1 is the **RUNNING** process of my own eflags diff-test framework, instead of just initialization.  

Consider instruction `imull  %edi, %eax` . According to Intel x86 Manual, the SF, ZF flags are **undefined**. Since after the execution of this instruction, SF/ZF can be any value, it's meaningless to check them, so we have to ignore SF/ZF after the instruction. 

As for the bug, I ignored the flag for just one eflags checkpoint(right after the instruction), **but this is not enough**, since consecutive non-eflags instructions like `mov` will **keep the state** which is still different from that in QEMU, then it will assert at the next EFLAGS checkpoint. As a result, we have to **remember** what to ignore (and **forget** them when any eflags setter is carried), or there will be too many false-positives. 

I solves the problem with https://github.com/FluorineDog/hust-pa/commit/d65b83a60e0afb968cfba5d94547f3e2810986b4 and https://github.com/FluorineDog/hust-pa/commit/c60f5db93ac883f9700a0ceb1ff4dbfcf48b4080. You may read the code if you are interested.

**Comment by Michael1015198808** [comment]
Thank you for your reply!
I agree with your considaration about undifined states of EFLAGS. And your solution is interesting, too. 
Since you have considered and solved these two problems, I would like to talk something more.
This potential bug is considered in the frame and be highlighted in our ICS course. So you can find this problem independently shows that you're a good CSer!
If you'd like to see how the framework consider and solve this problem. You can check `nemu/src/monitor/diff-test/diff-test.c`, function `difftest_skip_ref` and `ref_difftest_setregs` are functions solve the problem you considered, what in a total different way.

**Comment by FluorineDog** [comment]
Before clicking your link, I guess your solution is just to copy undefined flags in NEMU to QEMU. This is a much simpler solution, which I had actually considered when designing my solution. 

However, though technically it is not wrong, I finally determined that letting NEMU interfere the standard execution process is **inherently evil**. Since you will have **different execution flows with and without diff-test**, this solution is not acceptable for me.

**Comment by FluorineDog** [comment]
since no further discussion, issus closed
